### ISSUE TITLE
Database access problem

### ISSUE THREAD

**Issue by bmagic** [galedric/guild-tools#69]
I have installed your guild-tools and on the first launch when I try to had a character, I have this error :
> DEBUG - insert into `gt_chars` (`name`,`server`,`owner`,`main`,`active`,`class`,`race`,`gender`,`level`,`achievements`,`thumbnail`,`ilvl`,`role`,`invalid`,`last_update`)  values ('Debian','dalaran',48,false,true,1,6,0,100,8345,'marecage-de-zangar/64/89442880-avatar.jpg',633,'TANK',false,1424899665706)
> ERROR - Database access problem. Killing off this connection and all remaining connections in the connection pool. SQL State = HY000

Any tips because the sql string is correct and can be launch in mysql term.

**Comment by bmagic** [comment]
Ok I found it ... sorry ... 
I have add Auto Increment on Id column of gt_chars table.

**Comment by galedric** [comment]
The database template data seem to be incomplete. I need to fix the wiki page.
